version: '3.8'

services:
  # book-catalog microservice
  book-catalog:
    build:
      context: ./book_catalog 
      dockerfile: Dockerfile  
    container_name: book-catalog
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL= postgresql://book_inventory_4j9c_user:TcN8cizZO65r57gQcwqYx2Wt616F1lvK@dpg-crl7ag56l47c73fsut10-a.oregon-postgres.render.com/book_inventory_4j9c

  # inventory-management microservice
  inventory-management:
    build:
      context: ./inventory_management 
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL= postgresql://book_inventory_4j9c_user:TcN8cizZO65r57gQcwqYx2Wt616F1lvK@dpg-crl7ag56l47c73fsut10-a.oregon-postgres.render.com/book_inventory_4j9c