name: Infrastrcture Terraform Destroy

on:
  workflow_dispatch:  

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform init
      working-directory: ./scripts/terraform
      run: terraform init

    # Terraform validate before destroy
    - name: Terraform Validate
      working-directory: ./scripts/terraform
      run: terraform validate

    # Destroy the infrastructure
    - name: Terraform Destroy
      working-directory: ./scripts/terraform
      run: terraform destroy -auto-approve -var "resource_group_name=booksApp"

    # Refresh Terraform state
    - name: Refresh terraform
      working-directory: ./scripts/terraform  
      run: terraform refresh